// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaVision.Infrastructure.Data;

#nullable disable

namespace NovaVision.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NovaVisionDbContext))]
    [Migration("20260331071458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NovaVision.Core.Entities.Licence", b =>
                {
                    b.Property<int>("LicenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IncludesNec")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesNet")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesVrt")
                        .HasColumnType("bit");

                    b.Property<string>("LicenceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LicenceId");

                    b.HasIndex("LicenceKey")
                        .IsUnique();

                    b.ToTable("Licences");
                });

            modelBuilder.Entity("NovaVision.Core.Entities.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficeId");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("NovaVision.Core.Entities.ScreenCalibration", b =>
                {
                    b.Property<int>("ScreenCalibrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScreenCalibrationId"));

                    b.Property<DateTime>("CalibratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DegreePixels")
                        .HasColumnType("float");

                    b.Property<double>("DevicePixelRatio")
                        .HasColumnType("float");

                    b.Property<double>("DistanceCm")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PixelsPerCm")
                        .HasColumnType("float");

                    b.Property<int>("ScreenHeight")
                        .HasColumnType("int");

                    b.Property<int>("ScreenWidth")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ScreenCalibrationId");

                    b.HasIndex("UserId");

                    b.ToTable("ScreenCalibrations");
                });

            modelBuilder.Entity("NovaVision.Core.Entities.UserDetail", b =>
                {
                    b.Property<int>("UserDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDetailId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlindnessSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlindnessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DegreePixels")
                        .HasColumnType("float");

                    b.Property<bool>("DiagnosticComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("DiagnosticFailed")
                        .HasColumnType("bit");

                    b.Property<string>("DiagnosticType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FixationColour1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixationColour2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixationShape1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixationShape2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InjuryCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InjuryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NecComplete")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NecEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NetComplete")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NetEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ScreenDistance")
                        .HasColumnType("float");

                    b.Property<double?>("ScreenHeight")
                        .HasColumnType("float");

                    b.Property<double?>("ScreenWidth")
                        .HasColumnType("float");

                    b.Property<double?>("Size")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestEye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TherapyBlock")
                        .HasColumnType("int");

                    b.Property<int>("TherapyLevel")
                        .HasColumnType("int");

                    b.Property<int>("TherapyPart")
                        .HasColumnType("int");

                    b.Property<int>("TherapyRepeat")
                        .HasColumnType("int");

                    b.Property<int>("TherapyStage")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VrtComplete")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VrtEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserDetailId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("NovaVision.Identity.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ClinicianUserId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en-GB");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NovaVision.Therapy.Nec.Entities.NecSessionResult", b =>
                {
                    b.Property<int>("NecSessionResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NecSessionResultId"));

                    b.Property<int>("CorrectClicks")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("float");

                    b.Property<int>("IncorrectClicks")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MissedTargets")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NecTherapyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalTargets")
                        .HasColumnType("int");

                    b.HasKey("NecSessionResultId");

                    b.HasIndex("NecTherapyId");

                    b.ToTable("NecSessionResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Nec.Entities.NecTherapy", b =>
                {
                    b.Property<int>("NecTherapyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NecTherapyId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NecTherapyId");

                    b.HasIndex("UserId");

                    b.ToTable("NecTherapies");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetSessionResult", b =>
                {
                    b.Property<int>("NetSessionResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NetSessionResultId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NetTherapyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.HasKey("NetSessionResultId");

                    b.HasIndex("NetTherapyId");

                    b.ToTable("NetSessionResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetSessionResultTarget", b =>
                {
                    b.Property<long>("NetSessionResultTargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NetSessionResultTargetId"));

                    b.Property<double>("Contrast")
                        .HasColumnType("float");

                    b.Property<int>("Correct")
                        .HasColumnType("int");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<int>("NetSessionResultId")
                        .HasColumnType("int");

                    b.Property<int>("Presented")
                        .HasColumnType("int");

                    b.Property<int>("TargetNumber")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("NetSessionResultTargetId");

                    b.HasIndex("NetSessionResultId");

                    b.ToTable("NetSessionResultTargets");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetTherapy", b =>
                {
                    b.Property<int>("NetTherapyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NetTherapyId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("LowerLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTargets")
                        .HasColumnType("int");

                    b.Property<bool>("PracticeComplete")
                        .HasColumnType("bit");

                    b.Property<double>("PracticeContrast")
                        .HasColumnType("float");

                    b.Property<double>("PracticeDiameter")
                        .HasColumnType("float");

                    b.Property<int>("PracticePresentations")
                        .HasColumnType("int");

                    b.Property<double>("PracticeX")
                        .HasColumnType("float");

                    b.Property<double>("PracticeY")
                        .HasColumnType("float");

                    b.Property<int>("Presentations")
                        .HasColumnType("int");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("UpperLimit")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NetTherapyId");

                    b.HasIndex("UserId");

                    b.ToTable("NetTherapies");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetTherapyTarget", b =>
                {
                    b.Property<int>("NetTherapyTargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NetTherapyTargetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentContrast")
                        .HasColumnType("float");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NetTherapyId")
                        .HasColumnType("int");

                    b.Property<double>("StartContrast")
                        .HasColumnType("float");

                    b.Property<int>("TargetNumber")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("NetTherapyTargetId");

                    b.HasIndex("NetTherapyId");

                    b.ToTable("NetTherapyTargets");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtBlockResult", b =>
                {
                    b.Property<int>("VrtBlockResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrtBlockResultId"));

                    b.Property<double>("AverageResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgResponseTimeBLMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgResponseTimeBRMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgResponseTimeTLMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgResponseTimeTRMs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("FalsePositives")
                        .HasColumnType("int");

                    b.Property<int>("FixationChanges")
                        .HasColumnType("int");

                    b.Property<int>("FixationCorrect")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<double>("MaxResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<double>("MinResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<int>("StimuliCorrect")
                        .HasColumnType("int");

                    b.Property<int>("StimuliPresented")
                        .HasColumnType("int");

                    b.Property<int>("VrtTherapyBlockId")
                        .HasColumnType("int");

                    b.HasKey("VrtBlockResultId");

                    b.HasIndex("VrtTherapyBlockId");

                    b.ToTable("VrtBlockResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtFixationResult", b =>
                {
                    b.Property<long>("VrtFixationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VrtFixationResultId"));

                    b.Property<bool>("Correct")
                        .HasColumnType("bit");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("Presented")
                        .HasColumnType("bit");

                    b.Property<double>("ResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("VrtBlockResultId")
                        .HasColumnType("int");

                    b.HasKey("VrtFixationResultId");

                    b.HasIndex("VrtBlockResultId");

                    b.ToTable("VrtFixationResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtStimulusResult", b =>
                {
                    b.Property<long>("VrtStimulusResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VrtStimulusResultId"));

                    b.Property<bool>("Correct")
                        .HasColumnType("bit");

                    b.Property<int>("GridX")
                        .HasColumnType("int");

                    b.Property<int>("GridY")
                        .HasColumnType("int");

                    b.Property<bool>("Presented")
                        .HasColumnType("bit");

                    b.Property<string>("Quadrant")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<double>("ResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("VrtBlockResultId")
                        .HasColumnType("int");

                    b.HasKey("VrtStimulusResultId");

                    b.HasIndex("VrtBlockResultId");

                    b.ToTable("VrtStimulusResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtTherapy", b =>
                {
                    b.Property<int>("VrtTherapyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrtTherapyId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("GridAngle")
                        .HasColumnType("float");

                    b.Property<int>("GridSizeX")
                        .HasColumnType("int");

                    b.Property<int>("GridSizeY")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("VrtTherapyId");

                    b.HasIndex("UserId");

                    b.ToTable("VrtTherapies");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtTherapyBlock", b =>
                {
                    b.Property<int>("VrtTherapyBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrtTherapyBlockId"));

                    b.Property<int>("BlockNumber")
                        .HasColumnType("int");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExcludeCentre")
                        .HasColumnType("bit");

                    b.Property<string>("FixationColour1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FixationColour2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FixationDisplayTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("FixationMaxDelayTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("FixationMinResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<double>("FixationRate")
                        .HasColumnType("float");

                    b.Property<string>("FixationShape1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FixationShape2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("FixationVariance")
                        .HasColumnType("float");

                    b.Property<double>("GridAngle")
                        .HasColumnType("float");

                    b.Property<int>("GridSizeX")
                        .HasColumnType("int");

                    b.Property<int>("GridSizeY")
                        .HasColumnType("int");

                    b.Property<int>("MaxIntervalMs")
                        .HasColumnType("int");

                    b.Property<int>("MinIntervalMs")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgressStimuliCount")
                        .HasColumnType("int");

                    b.Property<int>("SessionRepeats")
                        .HasColumnType("int");

                    b.Property<int>("SessionStimuli")
                        .HasColumnType("int");

                    b.Property<string>("StimulusColour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("StimulusDiameter")
                        .HasColumnType("float");

                    b.Property<int>("StimulusDisplayTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("StimulusMaxDelayTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("StimulusMinResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("StimulusShape")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TherapyArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tolerance")
                        .HasColumnType("int");

                    b.Property<int>("VrtTherapyId")
                        .HasColumnType("int");

                    b.HasKey("VrtTherapyBlockId");

                    b.HasIndex("VrtTherapyId");

                    b.ToTable("VrtTherapyBlocks");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtTherapySchedule", b =>
                {
                    b.Property<int>("VrtTherapyScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrtTherapyScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sessions")
                        .HasColumnType("int");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("VrtTherapyBlockId")
                        .HasColumnType("int");

                    b.Property<int>("VrtTherapyId")
                        .HasColumnType("int");

                    b.HasKey("VrtTherapyScheduleId");

                    b.HasIndex("VrtTherapyBlockId");

                    b.HasIndex("VrtTherapyId");

                    b.ToTable("VrtTherapySchedules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("NovaVision.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("NovaVision.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaVision.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("NovaVision.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NovaVision.Therapy.Nec.Entities.NecSessionResult", b =>
                {
                    b.HasOne("NovaVision.Therapy.Nec.Entities.NecTherapy", "Therapy")
                        .WithMany("SessionResults")
                        .HasForeignKey("NecTherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetSessionResult", b =>
                {
                    b.HasOne("NovaVision.Therapy.Net.Entities.NetTherapy", "Therapy")
                        .WithMany("SessionResults")
                        .HasForeignKey("NetTherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetSessionResultTarget", b =>
                {
                    b.HasOne("NovaVision.Therapy.Net.Entities.NetSessionResult", "SessionResult")
                        .WithMany("TargetResults")
                        .HasForeignKey("NetSessionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionResult");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetTherapyTarget", b =>
                {
                    b.HasOne("NovaVision.Therapy.Net.Entities.NetTherapy", "Therapy")
                        .WithMany("Targets")
                        .HasForeignKey("NetTherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtBlockResult", b =>
                {
                    b.HasOne("NovaVision.Therapy.Vrt.Entities.VrtTherapyBlock", "Block")
                        .WithMany("Results")
                        .HasForeignKey("VrtTherapyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtFixationResult", b =>
                {
                    b.HasOne("NovaVision.Therapy.Vrt.Entities.VrtBlockResult", "BlockResult")
                        .WithMany("FixationResults")
                        .HasForeignKey("VrtBlockResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockResult");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtStimulusResult", b =>
                {
                    b.HasOne("NovaVision.Therapy.Vrt.Entities.VrtBlockResult", "BlockResult")
                        .WithMany("StimulusResults")
                        .HasForeignKey("VrtBlockResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockResult");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtTherapyBlock", b =>
                {
                    b.HasOne("NovaVision.Therapy.Vrt.Entities.VrtTherapy", "Therapy")
                        .WithMany("Blocks")
                        .HasForeignKey("VrtTherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtTherapySchedule", b =>
                {
                    b.HasOne("NovaVision.Therapy.Vrt.Entities.VrtTherapyBlock", "Block")
                        .WithMany()
                        .HasForeignKey("VrtTherapyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaVision.Therapy.Vrt.Entities.VrtTherapy", "Therapy")
                        .WithMany("Schedules")
                        .HasForeignKey("VrtTherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("NovaVision.Therapy.Nec.Entities.NecTherapy", b =>
                {
                    b.Navigation("SessionResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetSessionResult", b =>
                {
                    b.Navigation("TargetResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Net.Entities.NetTherapy", b =>
                {
                    b.Navigation("SessionResults");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtBlockResult", b =>
                {
                    b.Navigation("FixationResults");

                    b.Navigation("StimulusResults");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtTherapy", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("NovaVision.Therapy.Vrt.Entities.VrtTherapyBlock", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
